[licenses]
unlicensed = "warn"
allow-osi-fsf-free = "both"
copyleft = "deny"
default = "warn"
unused-allowed-license = "warn"
confidence-threshold = 0.95
allow = [
    "MIT",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "0BSD",
    "BSD-3-Clause",
    "ISC",
    "OFL-1.1",
    "BSL-1.0",
    "BSD-2-Clause",
    "LicenseRef-UFL-1.0",
    "Zlib",
    "Unicode-DFS-2016",
]
[bans]
multiple-versions="allow"

[advisories]
unmaintained = "allow"
vulnerability = "allow"

[licenses.private]
ignore = true
